title: Dr. Matteo Icardi
description: Associate Professor in Applied Mathematics, University of Nottingham
theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

navigation:
  - title: Home
    url: /index.html
  - title: Coding
    url: /coding.html
  - title: Maths
    url: /maths.html
  - title: Industrial Applications
    url: /industrial_applications.html
  - title: Research
    url: /research.html
  - title: Grants
    url: /grants.html
  - title: CFD/OpenFOAM
    url: /cfd_openfoam.html

# Exclude unnecessary files from the build
exclude:
  - some_content.txt
  - .DS_Store
